title: kastore
author: Tskit Developers
copyright: "2026"
only_build_toc_files: true

execute:
  execute_notebooks: cache

repository:
  url: https://github.com/tskit-dev/kastore
  branch: main
  path_to_book: docs

html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

sphinx:
  extra_extensions:
  - breathe
  - sphinx.ext.autodoc
  - sphinx.ext.intersphinx
  - sphinx.ext.todo
  - sphinx_issues

  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      pygments_dark_style: monokai
      navigation_with_keys: false
      logo:
        text: "kastore __PKG_VERSION__"
      repository_url: https://github.com/tskit-dev/kastore
      repository_branch: main
      path_to_docs: docs
      use_repository_button: true
      use_edit_page_button: true
      use_issues_button: true
    pygments_style: monokai
    issues_github_path: tskit-dev/kastore
    todo_include_todos: true
    intersphinx_mapping:
      python: ["https://docs.python.org/3/", null]
    breathe_projects:
      kastore: doxygen/xml
    breathe_default_project: kastore
    breathe_domain_by_extension:
      h: c
    breathe_show_define_initializer: true
    nitpick_ignore_regex: [
        ["c:identifier", "FILE"],
        ["c:identifier", "size_t"],
        ["c:identifier", "int8_t"],
        ["c:identifier", "uint8_t"],
        ["c:identifier", "int16_t"],
        ["c:identifier", "uint16_t"],
        ["c:identifier", "int32_t"],
        ["c:identifier", "uint32_t"],
        ["c:identifier", "int64_t"],
        ["c:identifier", "uint64_t"],
    ]
